const estado = {
  favoritos: JSON.parse(localStorage.getItem('bitaFavoritos')) || [],
  carrito: JSON.parse(localStorage.getItem('bitaCarrito')) || [],
  destinoSeleccionado: '', usuario: JSON.parse(sessionStorage.getItem('bitaUsuarioSesion')) || JSON.parse(localStorage.getItem('bitaUsuario')) || null,
  reservas: JSON.parse(localStorage.getItem('bitaReservas')) || []
};
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const tarjetas = $$('.tarjeta-destino');
const datosViajes = { 'Japón': ['USD 2.850', '12 días', 'Cultural'], 'Italia': ['USD 1.950', '10 días', 'Gastronomía'], 'Marruecos': ['USD 1.780', '9 días', 'Aventura'], 'Australia': ['USD 3.400', '14 días', 'Naturaleza'], 'Corea del Sur': ['USD 2.490', '11 días', 'Cultural'], 'México': ['USD 1.050', '8 días', 'Relax'], 'Kenia': ['USD 3.150', '10 días', 'Safari'], 'Nueva Zelanda': ['USD 3.650', '14 días', 'Aventura'] };
const datosDestinos = {
  'Polonia': { titulo: 'Polonia esencial', descripcion: 'Historia, castillos y cultura en Varsovia y Cracovia.', precio: 1200, duracion: '8 días', tipo: 'Cultural' },
  'Bolivia': { titulo: 'Bolivia: Salar de Uyuni', descripcion: 'Altiplano, cultura andina y paisajes que parecen de otro mundo.', precio: 990, duracion: '7 días', tipo: 'Aventura' },
  'Suiza': { titulo: 'Suiza alpina', descripcion: 'Trenes panorámicos, lagos y pueblos de montaña.', precio: 2100, duracion: '9 días', tipo: 'Naturaleza' },
  'Japón': { titulo: 'Japón esencial', descripcion: 'Tradición, tecnología y cerezos en flor.', precio: 2850, duracion: '12 días', tipo: 'Cultural' },
  'Brasil': { titulo: 'Brasil: Río y playas', descripcion: 'Música, gastronomía y paisajes de la costa brasileña.', precio: 780, duracion: '7 días', tipo: 'Relax' },
  'Italia': { titulo: 'Italia entre sabores', descripcion: 'Roma, Florencia y Venecia en un recorrido inolvidable.', precio: 1950, duracion: '10 días', tipo: 'Gastronomía' },
  'México': { titulo: 'México Caribe', descripcion: 'Cenotes, cultura maya y descanso junto al mar.', precio: 1050, duracion: '8 días', tipo: 'Relax' },
  'Egipto': { titulo: 'Misterios de Egipto', descripcion: 'Pirámides, Nilo y templos de una civilización milenaria.', precio: 2300, duracion: '10 días', tipo: 'Cultural' },
  'Australia': { titulo: 'Australia salvaje', descripcion: 'Ciudades vibrantes, arrecifes y naturaleza única.', precio: 3400, duracion: '14 días', tipo: 'Naturaleza' },
  'Tailandia': { titulo: 'Tailandia esencial', descripcion: 'Templos, sabores y playas tropicales.', precio: 1690, duracion: '9 días', tipo: 'Cultural' },
  'Corea del Sur': { titulo: 'Corea del Sur', descripcion: 'Seúl, tradición y cultura contemporánea.', precio: 2490, duracion: '11 días', tipo: 'Cultural' },
  'Marruecos': { titulo: 'Colores de Marruecos', descripcion: 'Medinas, desierto y noches bajo las estrellas.', precio: 1780, duracion: '9 días', tipo: 'Aventura' },
  'Kenia': { titulo: 'Safari en Kenia', descripcion: 'Fauna salvaje y paisajes de sabana.', precio: 3150, duracion: '10 días', tipo: 'Safari' },
  'Nueva Zelanda': { titulo: 'Nueva Zelanda épica', descripcion: 'Glaciares, fiordos y rutas de película.', precio: 3650, duracion: '14 días', tipo: 'Aventura' }
};
let temporizadorAviso;
let monedaARS = false;
function dinero(valor) { const monto = Number(valor); return monedaARS ? `ARS ${(monto * 1100).toLocaleString('es-AR')}` : `USD ${monto.toLocaleString('es-AR')}`; }
let perfiles = JSON.parse(localStorage.getItem('bitaPerfiles')) || [];
if (estado.usuario && !perfiles.some((perfil) => perfil.correo === estado.usuario.correo)) perfiles.push({ ...estado.usuario });
function guardarEstado() { localStorage.setItem('bitaFavoritos', JSON.stringify(estado.favoritos)); localStorage.setItem('bitaCarrito', JSON.stringify(estado.carrito)); localStorage.setItem('bitaPerfiles', JSON.stringify(perfiles)); localStorage.setItem('bitaReservas', JSON.stringify(estado.reservas)); }
function guardarSesion(recordar = false) { sessionStorage.setItem('bitaUsuarioSesion', JSON.stringify(estado.usuario)); if (recordar) localStorage.setItem('bitaUsuario', JSON.stringify(estado.usuario)); else localStorage.removeItem('bitaUsuario'); guardarEstado(); }
function cerrarSesion() { estado.usuario = null; sessionStorage.removeItem('bitaUsuarioSesion'); localStorage.removeItem('bitaUsuario'); guardarEstado(); actualizarUsuario(); }
async function hashClave(clave) { if (window.crypto?.subtle) { const datos = new TextEncoder().encode(clave); const hash = await crypto.subtle.digest('SHA-256', datos); return [...new Uint8Array(hash)].map((byte) => byte.toString(16).padStart(2, '0')).join(''); } return `local-${[...clave].reduce((total, letra) => ((total << 5) - total + letra.charCodeAt(0)) | 0, 0)}`; }
function mostrarAviso(mensaje) { clearTimeout(temporizadorAviso); $('#aviso').textContent = mensaje; $('#aviso').classList.add('visible'); temporizadorAviso = setTimeout(() => $('#aviso').classList.remove('visible'), 3200); }
function abrir(selector) { $(selector).classList.add('abierto'); $(selector).setAttribute('aria-hidden', 'false'); }
function cerrar(selector) { $(selector).classList.remove('abierto'); $(selector).setAttribute('aria-hidden', 'true'); }
function actualizarFavoritos() { $('#contador-favoritos').textContent = estado.favoritos.length; tarjetas.forEach((tarjeta) => { const activo = estado.favoritos.includes(tarjeta.dataset.destino); const boton = tarjeta.querySelector('.corazon'); boton.textContent = activo ? '♥' : '♡'; boton.classList.toggle('seleccionado', activo); }); }
function actualizarUsuario() { $$('[data-cuenta-acceso]').forEach((boton) => { const nombre = estado.usuario?.nombre?.split(' ')[0]; boton.dataset.accion = estado.usuario ? 'abrir-cuenta' : 'abrir-login'; boton.setAttribute('aria-label', estado.usuario ? 'Abrir mi cuenta' : 'Iniciar sesión o crear una cuenta'); const texto = boton.querySelector('.texto-cuenta'); if (texto) texto.textContent = boton.classList.contains('boton-cuenta') ? (nombre ? `Hola, ${nombre}` : 'Mi cuenta') : (estado.usuario ? 'Mi cuenta' : 'Cuenta'); }); }
function actualizarCarrito() {
  const cantidad = estado.carrito.reduce((total, item) => total + item.cantidad, 0); const subtotal = estado.carrito.reduce((total, item) => total + item.precio * item.cantidad, 0); const impuestos = Math.round(subtotal * 0.08);
  $('#contador-carrito').textContent = cantidad; $('#subtotal-carrito').textContent = dinero(subtotal); $('#impuestos-carrito').textContent = dinero(impuestos); $('#total-carrito').textContent = dinero(subtotal + impuestos);
  $('#items-carrito').innerHTML = estado.carrito.length ? estado.carrito.map((item, indice) => `<article class="item-carrito"><div><h3>${item.nombre}</h3><p>${item.noches} · ${dinero(item.precio)} por persona</p><div class="cantidad"><button type="button" data-accion="restar" data-indice="${indice}">−</button><span>${item.cantidad}</span><button type="button" data-accion="sumar" data-indice="${indice}">+</button></div></div><button type="button" class="eliminar-item" data-accion="eliminar" data-indice="${indice}" aria-label="Eliminar ${item.nombre}">×</button></article>`).join('') : '<div class="carrito-vacio"><span>✈</span><h3>Tu carrito está vacío</h3><p>Agregá un paquete y empezá a organizar tu próxima aventura.</p></div>';
  guardarEstado();
}
function agregarCarrito(paquete) { const existente = estado.carrito.find((item) => item.nombre === paquete.nombre); if (existente) existente.cantidad += 1; else estado.carrito.push({ ...paquete, cantidad: 1 }); actualizarCarrito(); mostrarAviso(`${paquete.nombre} se agregó al carrito.`); }
function abrirDetalle(destino, precio) { estado.destinoSeleccionado = destino; const precioVisible = /^\d+$/.test(String(precio)) ? dinero(Number(precio)) : precio; $('#modal-titulo').textContent = `Viaje a ${destino}`; $('#modal-texto').innerHTML = `Este programa está disponible desde <b>${precioVisible}</b> por persona.<br><br><b>Incluye:</b> alojamiento seleccionado, asistencia al viajero y guía local.<br><b>Itinerario:</b> llegada y bienvenida · recorridos destacados · día libre · regreso.<br><br>Elegí tu fecha y te enviamos una propuesta personalizada.`; abrir('#modal'); }
function prepararTarjetasDestinos() { tarjetas.forEach((tarjeta) => { const datos = datosDestinos[tarjeta.dataset.destino]; if (!datos) return; tarjeta.dataset.precio = datos.precio; tarjeta.dataset.noches = datos.duracion; const info = tarjeta.querySelector('.info-destino'); info.querySelector('h3').textContent = datos.titulo; info.querySelector('p').textContent = datos.descripcion; const precio = info.querySelector('span:not(.chip)'); precio.textContent = `Desde ${dinero(datos.precio)}`; precio.dataset.usd = datos.precio; let meta = info.querySelector('.meta-destino'); if (!meta) { meta = document.createElement('small'); meta.className = 'meta-destino'; precio.before(meta); } meta.textContent = `${datos.duracion} · ${datos.tipo}`; const favorito = tarjeta.querySelector('.corazon'); favorito.setAttribute('aria-label', `Agregar ${tarjeta.dataset.destino} a favoritos`); const acciones = tarjeta.querySelector('.acciones-tarjeta'); if (!acciones.querySelector('.comprar-destino')) { const comprar = document.createElement('button'); comprar.type = 'button'; comprar.className = 'comprar-destino'; comprar.textContent = 'Agregar viaje'; comprar.setAttribute('aria-label', `Agregar ${tarjeta.dataset.destino} al carrito`); acciones.prepend(comprar); } }); }
function activarAuth(tipo) {
  const esLogin = tipo === 'login'; const esRegistro = tipo === 'registro';
  $$('.pestana').forEach((p) => { const activa = p.dataset.auth === tipo; p.classList.toggle('activa', activa); p.setAttribute('aria-selected', String(activa)); });
  $('#form-login').classList.toggle('oculto', !esLogin); $('#form-registro').classList.toggle('oculto', !esRegistro); $('#form-recuperar').classList.toggle('oculto', tipo !== 'recuperar');
  const primerCampo = esLogin ? '#email-login' : esRegistro ? '#nombre-registro' : '#email-recuperar';
  $(primerCampo).focus();
}
function mensajeAuth(id, mensaje, tipo = '') { const elemento = $(id); elemento.textContent = mensaje; elemento.className = `mensaje-auth ${tipo}`; }
function abrirAuth(tipo = 'login') { abrir('#modal-auth'); activarAuth(tipo); }

$$('[data-accion="mostrar-buscador"]').forEach((boton) => boton.addEventListener('click', () => { abrir('#buscador'); $('#destino').focus(); }));
$('[data-accion="cerrar-buscador"]').addEventListener('click', () => cerrar('#buscador'));
$('[data-accion="cerrar-modal"]').addEventListener('click', () => cerrar('#modal'));
$$('[data-accion="abrir-carrito"]').forEach((boton) => boton.addEventListener('click', () => abrir('#carrito')));
$('[data-accion="cerrar-carrito"]').addEventListener('click', () => cerrar('#carrito'));
$('[data-accion="cerrar-auth"]').addEventListener('click', () => cerrar('#modal-auth'));
prepararTarjetasDestinos();
$$('[data-accion="ir-destinos"]').forEach((boton) => boton.addEventListener('click', () => { $('#paquetes').scrollIntoView({ behavior: 'smooth' }); mostrarAviso('Explorá nuestros paquetes y elegí tu próxima aventura.'); }));
$$('.filtro').forEach((boton) => boton.addEventListener('click', () => { $$('.filtro').forEach((item) => item.classList.remove('activo')); boton.classList.add('activo'); tarjetas.forEach((tarjeta) => tarjeta.classList.toggle('oculta', boton.dataset.filtro !== 'todos' && tarjeta.dataset.region !== boton.dataset.filtro)); }));
tarjetas.forEach((tarjeta) => { tarjeta.querySelector('.corazon').addEventListener('click', () => { const destino = tarjeta.dataset.destino; estado.favoritos = estado.favoritos.includes(destino) ? estado.favoritos.filter((item) => item !== destino) : [...estado.favoritos, destino]; guardarEstado(); actualizarFavoritos(); mostrarAviso(`${destino} ${estado.favoritos.includes(destino) ? 'se agregó a' : 'se quitó de'} tus favoritos.`); }); tarjeta.querySelector('.detalle').addEventListener('click', () => abrirDetalle(tarjeta.dataset.destino, tarjeta.dataset.precio)); tarjeta.querySelector('.comprar-destino').addEventListener('click', () => { const datos = datosDestinos[tarjeta.dataset.destino]; agregarCarrito({ nombre: datos.titulo, precio: datos.precio, noches: datos.duracion }); abrir('#carrito'); }); });
$('[data-accion="ver-favoritos"]').addEventListener('click', () => mostrarAviso(estado.favoritos.length ? `Tus favoritos: ${estado.favoritos.join(', ')}.` : 'Todavía no agregaste destinos a favoritos.'));
$('#form-busqueda').addEventListener('submit', (evento) => { evento.preventDefault(); const buscado = $('#destino').value.trim().toLowerCase(); const encontrado = tarjetas.find((t) => t.dataset.destino.toLowerCase().includes(buscado)); if (encontrado) { cerrar('#buscador'); abrirDetalle(encontrado.dataset.destino, encontrado.dataset.precio); } else $('#resultado-busqueda').textContent = `No encontramos “${buscado}”, pero podemos armar un viaje a medida.`; });
$$('.consultar').forEach((boton) => boton.addEventListener('click', () => { cerrar('#modal'); $('#contacto').scrollIntoView({ behavior: 'smooth' }); mostrarAviso(`Recibimos tu consulta sobre ${boton.dataset.destino || estado.destinoSeleccionado}.`); }));
$$('.boton-agregar').forEach((boton) => boton.addEventListener('click', () => { const paquete = boton.closest('.paquete'); agregarCarrito({ nombre: paquete.dataset.paquete, precio: Number(paquete.dataset.precio), noches: paquete.dataset.noches }); }));
$('#items-carrito').addEventListener('click', (evento) => { const boton = evento.target.closest('button'); if (!boton) return; const indice = Number(boton.dataset.indice); if (boton.dataset.accion === 'sumar') estado.carrito[indice].cantidad += 1; if (boton.dataset.accion === 'restar') { estado.carrito[indice].cantidad -= 1; if (!estado.carrito[indice].cantidad) estado.carrito.splice(indice, 1); } if (boton.dataset.accion === 'eliminar') estado.carrito.splice(indice, 1); actualizarCarrito(); });
$('[data-accion="vaciar-carrito"]').addEventListener('click', () => { if (!estado.carrito.length) return mostrarAviso('El carrito ya está vacío.'); estado.carrito = []; actualizarCarrito(); mostrarAviso('Se vació el carrito.'); });
function obtenerTotalCarrito() { const subtotal = estado.carrito.reduce((total, item) => total + item.precio * item.cantidad, 0); return { subtotal, impuestos: Math.round(subtotal * 0.08), total: subtotal + Math.round(subtotal * 0.08) }; }
function actualizarResumenCheckout() { const { subtotal, impuestos, total } = obtenerTotalCarrito(); $('#resumen-checkout').innerHTML = `<div class="resumen-checkout-titulo"><span>Tu selección</span><b>${estado.carrito.reduce((cantidad, item) => cantidad + item.cantidad, 0)} ${estado.carrito.reduce((cantidad, item) => cantidad + item.cantidad, 0) === 1 ? 'viaje' : 'viajes'}</b></div><div class="resumen-checkout-items">${estado.carrito.map((item) => `<p><span>${item.cantidad}× ${item.nombre}<small>${item.noches} · Por persona</small></span><strong>${dinero(item.precio * item.cantidad)}</strong></p>`).join('')}</div><div class="resumen-checkout-total"><p><span>Subtotal</span><strong>${dinero(subtotal)}</strong></p><p><span>Impuestos estimados</span><strong>${dinero(impuestos)}</strong></p><p class="total"><span>Total estimado</span><strong>${dinero(total)}</strong></p></div><small class="aclaracion-checkout">El precio final y la disponibilidad se confirman con un asesor antes de cualquier pago.</small>`; }
function abrirCheckout() { const hoy = new Date().toISOString().split('T')[0]; $('#salida-checkout').min = hoy; $('#nombre-checkout').value = estado.usuario?.nombre || ''; $('#email-checkout').value = estado.usuario?.correo || ''; $('#telefono-checkout').value = estado.usuario?.telefono || ''; $('#mensaje-checkout').textContent = ''; actualizarResumenCheckout(); abrir('#checkout'); }
$("[data-accion=\"checkout\"]").addEventListener('click', () => { if (!estado.carrito.length) return mostrarAviso('Agregá al menos un paquete para continuar.'); if (!estado.usuario) { cerrar('#carrito'); abrirAuth('login'); mostrarAviso('Iniciá sesión para continuar con la reserva.'); } else { cerrar('#carrito'); abrirCheckout(); } });
document.addEventListener('click', (evento) => { const boton = evento.target.closest('[data-accion="abrir-login"], [data-accion="abrir-cuenta"]'); if (!boton) return; if (boton.dataset.accion === 'abrir-login') abrirAuth('login'); else mostrarCuenta(); });
$$('.pestana').forEach((boton) => boton.addEventListener('click', () => activarAuth(boton.dataset.auth)));
$$('[data-accion="ir-registro"]').forEach((boton) => boton.addEventListener('click', () => activarAuth('registro')));
$$('[data-accion="ir-login"]').forEach((boton) => boton.addEventListener('click', () => activarAuth('login')));
$$('.ver-clave').forEach((boton) => boton.addEventListener('click', () => { const campo = $(`#${boton.dataset.clave}`); const visible = campo.type === 'text'; campo.type = visible ? 'password' : 'text'; boton.textContent = visible ? 'Mostrar' : 'Ocultar'; boton.setAttribute('aria-label', visible ? 'Mostrar contraseña' : 'Ocultar contraseña'); }));
$('#form-login').addEventListener('submit', async (evento) => {
  evento.preventDefault(); const formulario = evento.currentTarget;
  if (!formulario.checkValidity()) return formulario.reportValidity();
  const correo = $('#email-login').value.trim().toLowerCase(); const perfil = perfiles.find((item) => item.correo === correo);
  if (!perfil) return mensajeAuth('#mensaje-login', 'No encontramos una cuenta con ese correo. Creá una cuenta para continuar.', 'error');
  if (perfil.claveHash && perfil.claveHash !== await hashClave($('#clave-login').value)) return mensajeAuth('#mensaje-login', 'La contraseña no es correcta. Revisala o recuperá el acceso.', 'error');
  estado.usuario = { nombre: perfil.nombre, correo: perfil.correo, telefono: perfil.telefono || '' }; guardarSesion($('#recordar-sesion').checked); actualizarUsuario(); cerrar('#modal-auth'); formulario.reset(); mostrarAviso(`¡Qué bueno verte de nuevo, ${estado.usuario.nombre.split(' ')[0]}!`);
});
$('#form-registro').addEventListener('submit', async (evento) => {
  evento.preventDefault(); const formulario = evento.currentTarget;
  if (!formulario.checkValidity()) return formulario.reportValidity();
  const nombre = $('#nombre-registro').value.trim(); const correo = $('#email-registro').value.trim().toLowerCase(); const clave = $('#clave-registro').value; const confirmar = $('#confirmar-clave').value;
  if (!/[A-Z]/.test(clave) || !/\d/.test(clave)) return mensajeAuth('#mensaje-registro', 'Tu contraseña debe incluir una mayúscula y un número.', 'error');
  if (clave !== confirmar) return mensajeAuth('#mensaje-registro', 'Las contraseñas no coinciden. Revisalas e intentá otra vez.', 'error');
  if (perfiles.some((item) => item.correo === correo)) return mensajeAuth('#mensaje-registro', 'Ya existe una cuenta con ese correo. Iniciá sesión para continuar.', 'error');
  const perfil = { nombre, correo, telefono: $('#telefono-registro').value.trim(), recibeNovedades: $('#recibir-novedades').checked, claveHash: await hashClave(clave) };
  perfiles.push(perfil); estado.usuario = { nombre: perfil.nombre, correo: perfil.correo, telefono: perfil.telefono }; guardarSesion(true); actualizarUsuario(); cerrar('#modal-auth'); formulario.reset(); mensajeAuth('#mensaje-registro', ''); mostrarAviso(`¡Tu cuenta está lista, ${estado.usuario.nombre.split(' ')[0]}! Ya podés empezar a planear tu viaje.`);
});
$('[data-accion="recuperar-clave"]').addEventListener('click', () => activarAuth('recuperar'));
$('#form-recuperar').addEventListener('submit', (evento) => { evento.preventDefault(); const formulario = evento.currentTarget; if (!formulario.checkValidity()) return formulario.reportValidity(); mensajeAuth('#mensaje-recuperar', 'Registramos tu solicitud. La recuperación por correo se habilita al conectar el sistema de emails de BITA.', 'exito'); formulario.reset(); });
$('[data-accion="mostrar-asistencia"]').addEventListener('click', () => { $('#contacto').scrollIntoView({ behavior: 'smooth' }); mostrarAviso('Nuestro equipo está disponible para ayudarte.'); });
$('.boton-menu').addEventListener('click', (evento) => { const menu = $('.menu-principal'); menu.classList.toggle('abierto'); evento.currentTarget.setAttribute('aria-expanded', menu.classList.contains('abierto')); });
$$('.menu-principal a').forEach((enlace) => enlace.addEventListener('click', () => $('.menu-principal').classList.remove('abierto')));
actualizarFavoritos(); actualizarCarrito(); actualizarUsuario();

let segundosOferta = 8 * 60 * 60;
function actualizarOferta() { const h = Math.floor(segundosOferta / 3600); const m = Math.floor((segundosOferta % 3600) / 60); const s = segundosOferta % 60; $('#horas').textContent = String(h).padStart(2, '0'); $('#minutos').textContent = String(m).padStart(2, '0'); $('#segundos').textContent = String(s).padStart(2, '0'); if (segundosOferta > 0) segundosOferta -= 1; }
actualizarOferta(); setInterval(actualizarOferta, 1000);
$$('.pregunta').forEach((pregunta) => pregunta.addEventListener('click', () => { const abrirEsta = !pregunta.classList.contains('abierta'); $$('.pregunta').forEach((item) => { item.classList.remove('abierta'); item.nextElementSibling.classList.remove('visible'); item.querySelector('span').textContent = '+'; }); if (abrirEsta) { pregunta.classList.add('abierta'); pregunta.nextElementSibling.classList.add('visible'); pregunta.querySelector('span').textContent = '−'; } }));
function actualizarMoneda() { document.querySelectorAll('.paquete-pie strong,.info-destino>span,.ficha-cabecera strong').forEach((elemento) => { if (!elemento.dataset.usd) { const numero = elemento.textContent.replace(/[^0-9]/g, ''); elemento.dataset.usd = numero || '0'; } const precio = Number(elemento.dataset.usd); elemento.textContent = monedaARS ? `ARS ${(precio * 1100).toLocaleString('es-AR')}` : `USD ${precio.toLocaleString('es-AR')}`; }); }
$('[data-accion="cambiar-moneda"]').addEventListener('click', (e) => { monedaARS = !monedaARS; e.currentTarget.querySelector('b').textContent = monedaARS ? 'ARS' : 'USD'; actualizarMoneda(); actualizarCarrito(); mostrarAviso(`Precios mostrados en ${monedaARS ? 'pesos argentinos' : 'dólares estadounidenses'}.`); });
$$('[data-accion="comparar"]').forEach((boton) => boton.addEventListener('click', () => { const a = $('#comparar-a').value; const b = $('#comparar-b').value; if (!a || !b) { $('#resultado-comparador').textContent = 'Elegí dos destinos para poder compararlos.'; return; } const viajeA = datosViajes[a]; const viajeB = datosViajes[b]; $('#resultado-comparador').innerHTML = `<strong>Comparación rápida</strong><br>Precio: ${a} ${viajeA[0]} · ${b} ${viajeB[0]}<br>Duración: ${viajeA[1]} · ${viajeB[1]}<br>Experiencia: ${viajeA[2]} · ${viajeB[2]}`; }));
$$('[data-accion="ver-mapa"]').forEach((boton) => boton.addEventListener('click', () => { $('#viajes').scrollIntoView({ behavior: 'smooth' }); mostrarAviso('Usá los filtros de región para explorar los destinos.'); }));
$('[data-accion="oferta"]').addEventListener('click', () => { const bolivia = $('.tarjeta-destino.bolivia'); agregarCarrito({ nombre: 'Bolivia - Oferta relámpago', precio: 842, noches: '7 días' }); abrir('#carrito'); bolivia.scrollIntoView({ behavior: 'smooth' }); });
$('[data-accion="cerrar-checkout"]').addEventListener('click', () => cerrar('#checkout'));
$('#form-checkout').addEventListener('submit', (e) => {
  e.preventDefault(); const formulario = e.currentTarget;
  if (!formulario.checkValidity()) return formulario.reportValidity();
  if (!estado.carrito.length) return $('#mensaje-checkout').textContent = 'Tu selección está vacía. Volvé al carrito para elegir un viaje.';
  const { total } = obtenerTotalCarrito(); const codigo = `BITA-${Math.floor(100000 + Math.random() * 900000)}`;
  const reserva = { codigo, creadoEl: new Date().toLocaleDateString('es-AR'), nombre: $('#nombre-checkout').value.trim(), correo: $('#email-checkout').value.trim().toLowerCase(), telefono: $('#telefono-checkout').value.trim(), salida: $('#salida-checkout').value, pasajeros: $('#pasajeros-checkout').value, habitacion: $('#habitacion-checkout').value, comentarios: $('#comentarios-checkout').value.trim(), items: estado.carrito.map((item) => ({ ...item })), total, estado: 'Pendiente de confirmación' };
  estado.reservas.unshift(reserva); estado.carrito = []; guardarEstado(); actualizarCarrito(); cerrar('#checkout'); $('#texto-confirmacion').textContent = `Registramos tu solicitud ${codigo}. Un asesor te contactará para confirmar disponibilidad y precio final antes de cualquier pago.`; abrir('#confirmacion'); formulario.reset();
});
$('[data-accion="cerrar-confirmacion"]').addEventListener('click', () => cerrar('#confirmacion'));
$('[data-accion="abrir-chat"]').addEventListener('click', () => $('#chat').classList.add('abierto'));
$('[data-accion="cerrar-chat"]').addEventListener('click', () => $('#chat').classList.remove('abierto'));
$('#form-chat').addEventListener('submit', (e) => { e.preventDefault(); const texto = e.target.querySelector('input').value.trim(); $('#chat-mensajes').insertAdjacentHTML('beforeend', `<p class="mensaje-propio">${texto}</p>`); e.target.reset(); setTimeout(() => $('#chat-mensajes').insertAdjacentHTML('beforeend', '<p>Gracias, un asesor te responderá a la brevedad.</p>'), 500); });
function mostrarCuenta(tab = 'reservas') { if (!estado.usuario) { abrirAuth('login'); return; } const reservasUsuario = estado.reservas.filter((reserva) => reserva.correo === estado.usuario.correo); $('#nombre-cuenta').textContent = estado.usuario.nombre; $('#contenido-cuenta').innerHTML = tab === 'reservas' ? (reservasUsuario.length ? `<div class="lista-reservas">${reservasUsuario.map((reserva) => `<article class="reserva-cuenta"><span>${reserva.estado}</span><h3>${reserva.items.map((item) => item.nombre).join(' + ')}</h3><p>Código ${reserva.codigo} · Salida estimada: ${new Date(`${reserva.salida}T12:00:00`).toLocaleDateString('es-AR')}</p><strong>${dinero(reserva.total)} estimado</strong></article>`).join('')}</div>` : '<p>No tenés solicitudes todavía.</p><p>Cuando envíes una reserva, vas a poder seguirla desde acá.</p>') : tab === 'guardados' ? `<p>${estado.favoritos.length ? estado.favoritos.join(', ') : 'No guardaste destinos aún.'}</p>` : `<p><b>Correo:</b> ${estado.usuario.correo}</p><p><b>WhatsApp:</b> ${estado.usuario.telefono || 'No informado'}</p><button class="link-form" data-accion="cerrar-sesion">Cerrar sesión</button>`; $('#panel-cuenta').classList.add('abierto'); }
document.addEventListener('click', (e) => { const b = e.target.closest('[data-accion="cerrar-sesion"]'); if (b && b.closest('#panel-cuenta')) { cerrarSesion(); $('#panel-cuenta').classList.remove('abierto'); mostrarAviso('Sesión cerrada.'); } });
$$('.tabs-cuenta button').forEach((b) => b.addEventListener('click', () => mostrarCuenta(b.dataset.tab)));
$('[data-accion="cerrar-cuenta"]').addEventListener('click', () => $('#panel-cuenta').classList.remove('abierto'));
