const estado = {
  favoritos: JSON.parse(localStorage.getItem('bitaFavoritos')) || [],
  carrito: JSON.parse(localStorage.getItem('bitaCarrito')) || [],
  destinoSeleccionado: '', usuario: JSON.parse(sessionStorage.getItem('bitaUsuarioSesion')) || JSON.parse(localStorage.getItem('bitaUsuario')) || null,
  reservas: JSON.parse(localStorage.getItem('bitaReservas')) || []
};
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const tarjetas = $$('.tarjeta-destino');
const datosViajes = { 'Japón': ['USD 2.850', '12 días', 'Cultural'], 'Italia': ['USD 1.950', '10 días', 'Gastronomía'], 'Marruecos': ['USD 1.780', '9 días', 'Aventura'], 'Australia': ['USD 3.400', '14 días', 'Naturaleza'], 'Corea del Sur': ['USD 2.490', '11 días', 'Cultural'], 'México': ['USD 1.050', '8 días', 'Relax'], 'Kenia': ['USD 3.150', '10 días', 'Safari'], 'Nueva Zelanda': ['USD 3.650', '14 días', 'Aventura'] };
const datosDestinos = {
  'Polonia': { titulo: 'Polonia esencial', descripcion: 'Recorré Varsovia y Cracovia entre castillos, barrios históricos y una gastronomía que sorprende en cada parada.', precio: 1200, duracion: '8 días', tipo: 'Cultural' },
  'Bolivia': { titulo: 'Bolivia: Salar de Uyuni', descripcion: 'Explorá el altiplano, La Paz y el Salar de Uyuni: un paisaje inmenso y único, con cultura andina en cada recorrido.', precio: 990, duracion: '7 días', tipo: 'Aventura' },
  'Suiza': { titulo: 'Suiza alpina', descripcion: 'Viajá entre lagos turquesa, pueblos de montaña y trenes panorámicos que conectan algunas de las postales más lindas de Europa.', precio: 2100, duracion: '9 días', tipo: 'Naturaleza' },
  'Japón': { titulo: 'Japón esencial', descripcion: 'Viví el contraste entre la energía de Tokio, los templos de Kioto y una cultura donde tradición y tecnología conviven a diario.', precio: 2850, duracion: '12 días', tipo: 'Cultural' },
  'Brasil': { titulo: 'Brasil: Río y playas', descripcion: 'Combiná la energía de Río de Janeiro con playas, música y sabores locales en una escapada llena de color y ritmo.', precio: 780, duracion: '7 días', tipo: 'Relax' },
  'Italia': { titulo: 'Italia entre sabores', descripcion: 'Descubrí Roma, Florencia y Venecia a través de su arte, sus plazas y la cocina que convirtió a Italia en un clásico del viaje.', precio: 1950, duracion: '10 días', tipo: 'Gastronomía' },
  'México': { titulo: 'México Caribe', descripcion: 'Descansá frente al mar y sumá cenotes, ruinas mayas y gastronomía mexicana en una experiencia ideal para desconectar.', precio: 1050, duracion: '8 días', tipo: 'Relax' },
  'Egipto': { titulo: 'Misterios de Egipto', descripcion: 'Navegá entre historia y desierto: pirámides, templos y el Nilo en un recorrido por una de las civilizaciones más fascinantes del mundo.', precio: 2300, duracion: '10 días', tipo: 'Cultural' },
  'Australia': { titulo: 'Australia salvaje', descripcion: 'Recorré ciudades vibrantes, costas inmensas y paisajes naturales únicos, desde la bahía de Sídney hasta la Great Ocean Road.', precio: 3400, duracion: '14 días', tipo: 'Naturaleza' },
  'Tailandia': { titulo: 'Tailandia esencial', descripcion: 'Pasá de templos dorados y mercados llenos de aromas a playas tropicales, con la hospitalidad tailandesa como protagonista.', precio: 1690, duracion: '9 días', tipo: 'Cultural' },
  'Corea del Sur': { titulo: 'Corea del Sur', descripcion: 'Conocé Seúl, palacios históricos y barrios modernos en un viaje que mezcla cultura ancestral, diseño y gastronomía contemporánea.', precio: 2490, duracion: '11 días', tipo: 'Cultural' },
  'Marruecos': { titulo: 'Colores de Marruecos', descripcion: 'Perdete entre medinas, zocos y dunas del Sahara en un circuito de aromas, arquitectura y noches bajo el cielo del desierto.', precio: 1780, duracion: '9 días', tipo: 'Aventura' },
  'Kenia': { titulo: 'Safari en Kenia', descripcion: 'Viví safaris fotográficos en la sabana y observá fauna salvaje en libertad, con paisajes abiertos que definen África oriental.', precio: 3150, duracion: '10 días', tipo: 'Safari' },
  'Nueva Zelanda': { titulo: 'Nueva Zelanda épica', descripcion: 'Atravesá fiordos, glaciares y rutas panorámicas de película en un destino creado para viajeros que buscan naturaleza en grande.', precio: 3650, duracion: '14 días', tipo: 'Aventura' }
};
const guiasDestinos = {
  'Polonia': { circuito: 'Varsovia · Cracovia · Wieliczka', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Guía en español'], destacados: ['Llegada y bienvenida en Varsovia', 'Visita histórica por Varsovia', 'Traslado a Cracovia y recorrido guiado', 'Día libre y regreso'] },
  'Bolivia': { circuito: 'La Paz · Uyuni · Salar de Uyuni', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Excursión al Salar de Uyuni'], destacados: ['Llegada a La Paz y aclimatación', 'Ciudad de La Paz y miradores', 'Excursión por el Salar de Uyuni', 'Regreso y fin del programa'] },
  'Suiza': { circuito: 'Zúrich · Lucerna · Interlaken', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Trayecto panorámico en tren'], destacados: ['Llegada a Zúrich', 'Recorrido por Lucerna', 'Paisajes alpinos en Interlaken', 'Día libre y regreso'] },
  'Japón': { circuito: 'Tokio · Kioto · Osaka', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Excursión cultural guiada'], destacados: ['Llegada y primera noche en Tokio', 'Tokio entre tradición y tecnología', 'Tren hacia Kioto y templos', 'Tiempo libre y regreso'] },
  'Brasil': { circuito: 'Río de Janeiro · Costa Verde', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Excursión urbana en Río'], destacados: ['Llegada a Río de Janeiro', 'Cristo Redentor y panorámicas', 'Día de playa o Costa Verde', 'Tiempo libre y regreso'] },
  'Italia': { circuito: 'Roma · Florencia · Venecia', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Visitas guiadas seleccionadas'], destacados: ['Llegada a Roma', 'Historia y plazas de Roma', 'Arte y sabores de Florencia', 'Venecia y regreso'] },
  'México': { circuito: 'Cancún · Riviera Maya · Tulum', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Excursión a cenotes o Tulum'], destacados: ['Llegada al Caribe mexicano', 'Día libre de playa', 'Cenotes y cultura maya', 'Tiempo libre y regreso'] },
  'Egipto': { circuito: 'El Cairo · Luxor · Asuán', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Visitas a sitios arqueológicos'], destacados: ['Llegada a El Cairo', 'Pirámides de Giza', 'Templos y Nilo', 'Tiempo libre y regreso'] },
  'Australia': { circuito: 'Sídney · Melbourne · Great Ocean Road', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Excursión por Great Ocean Road'], destacados: ['Llegada a Sídney', 'Ciudad y bahía de Sídney', 'Melbourne y costa australiana', 'Tiempo libre y regreso'] },
  'Tailandia': { circuito: 'Bangkok · Chiang Mai · Phuket', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Visita a templos seleccionados'], destacados: ['Llegada a Bangkok', 'Templos y mercados locales', 'Naturaleza y cultura del norte', 'Playas y regreso'] },
  'Corea del Sur': { circuito: 'Seúl · Gyeongju · Busan', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Recorrido cultural guiado'], destacados: ['Llegada a Seúl', 'Palacios y barrios tradicionales', 'Historia de Gyeongju', 'Busan y regreso'] },
  'Marruecos': { circuito: 'Marrakech · Ait Ben Haddou · Desierto', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Noche de campamento en el desierto'], destacados: ['Llegada a Marrakech', 'Medina y zocos', 'Ruta hacia el desierto', 'Amanecer y regreso'] },
  'Kenia': { circuito: 'Nairobi · Masái Mara · Lago Naivasha', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Safaris fotográficos programados'], destacados: ['Llegada a Nairobi', 'Traslado a Masái Mara', 'Safari de día completo', 'Regreso y fin del programa'] },
  'Nueva Zelanda': { circuito: 'Auckland · Queenstown · Milford Sound', incluye: ['Alojamiento seleccionado', 'Desayunos diarios', 'Traslados principales', 'Excursión panorámica seleccionada'], destacados: ['Llegada a Auckland', 'Vuelo o traslado a Queenstown', 'Fiordos y paisajes de Milford Sound', 'Tiempo libre y regreso'] }
};
let temporizadorAviso;
let monedaARS = false;
let cotizacionDolarARS = Number(localStorage.getItem('bitaCotizacionDolarARS')) || 0;
let fechaCotizacionDolar = localStorage.getItem('bitaFechaCotizacionDolar') || '';
const DURACION_CACHE_COTIZACION = 30 * 60 * 1000;
function dinero(valor) { const monto = Number(valor); return monedaARS ? `ARS ${(monto * (cotizacionDolarARS || 1100)).toLocaleString('es-AR', { maximumFractionDigits: 0 })}` : `USD ${monto.toLocaleString('es-AR')}`; }
function actualizarEstadoCotizacion(mensaje = '') { const estadoCotizacion = $('#estado-cotizacion'); if (!estadoCotizacion) return; if (!monedaARS) { estadoCotizacion.textContent = 'Cotización oficial'; return; } estadoCotizacion.textContent = mensaje || (fechaCotizacionDolar ? `USD oficial · ${new Date(fechaCotizacionDolar).toLocaleTimeString('es-AR', { hour: '2-digit', minute: '2-digit' })}` : 'Actualizando cotización…'); }
async function cargarCotizacionDolar(forzar = false) { const cacheVigente = cotizacionDolarARS && fechaCotizacionDolar && Date.now() - new Date(fechaCotizacionDolar).getTime() < DURACION_CACHE_COTIZACION; if (cacheVigente && !forzar) { actualizarEstadoCotizacion(); return cotizacionDolarARS; } actualizarEstadoCotizacion('Actualizando cotización…'); try { const respuesta = await fetch('https://dolarapi.com/v1/dolares/oficial'); if (!respuesta.ok) throw new Error(`API ${respuesta.status}`); const datos = await respuesta.json(); if (!Number(datos.venta)) throw new Error('Cotización no disponible'); cotizacionDolarARS = Number(datos.venta); fechaCotizacionDolar = datos.fechaActualizacion || new Date().toISOString(); localStorage.setItem('bitaCotizacionDolarARS', String(cotizacionDolarARS)); localStorage.setItem('bitaFechaCotizacionDolar', fechaCotizacionDolar); actualizarEstadoCotizacion(); return cotizacionDolarARS; } catch (error) { actualizarEstadoCotizacion(cotizacionDolarARS ? 'Última cotización disponible' : 'Sin conexión · valor estimado'); return cotizacionDolarARS || 1100; } }
let perfiles = JSON.parse(localStorage.getItem('bitaPerfiles')) || [];
if (estado.usuario && !perfiles.some((perfil) => perfil.correo === estado.usuario.correo)) perfiles.push({ ...estado.usuario });
function guardarEstado() { localStorage.setItem('bitaFavoritos', JSON.stringify(estado.favoritos)); localStorage.setItem('bitaCarrito', JSON.stringify(estado.carrito)); localStorage.setItem('bitaPerfiles', JSON.stringify(perfiles)); localStorage.setItem('bitaReservas', JSON.stringify(estado.reservas)); }
function guardarSesion(recordar = false) { sessionStorage.setItem('bitaUsuarioSesion', JSON.stringify(estado.usuario)); if (recordar) localStorage.setItem('bitaUsuario', JSON.stringify(estado.usuario)); else localStorage.removeItem('bitaUsuario'); guardarEstado(); }
function cerrarSesion() { estado.usuario = null; sessionStorage.removeItem('bitaUsuarioSesion'); localStorage.removeItem('bitaUsuario'); guardarEstado(); actualizarUsuario(); }
async function hashClave(clave) { if (window.crypto?.subtle) { const datos = new TextEncoder().encode(clave); const hash = await crypto.subtle.digest('SHA-256', datos); return [...new Uint8Array(hash)].map((byte) => byte.toString(16).padStart(2, '0')).join(''); } return `local-${[...clave].reduce((total, letra) => ((total << 5) - total + letra.charCodeAt(0)) | 0, 0)}`; }
function mostrarAviso(mensaje) { clearTimeout(temporizadorAviso); $('#aviso').textContent = mensaje; $('#aviso').classList.add('visible'); temporizadorAviso = setTimeout(() => $('#aviso').classList.remove('visible'), 3200); }
function abrir(selector) { $(selector).classList.add('abierto'); $(selector).setAttribute('aria-hidden', 'false'); }
function cerrar(selector) { $(selector).classList.remove('abierto'); $(selector).setAttribute('aria-hidden', 'true'); }
function actualizarFavoritos() { $('#contador-favoritos').textContent = estado.favoritos.length; tarjetas.forEach((tarjeta) => { const activo = estado.favoritos.includes(tarjeta.dataset.destino); const boton = tarjeta.querySelector('.corazon'); boton.textContent = activo ? '♥' : '♡'; boton.classList.toggle('seleccionado', activo); }); }
function actualizarUsuario() { $$('[data-cuenta-acceso]').forEach((boton) => { const nombre = estado.usuario?.nombre?.split(' ')[0]; boton.dataset.accion = estado.usuario ? 'abrir-cuenta' : 'abrir-login'; boton.setAttribute('aria-label', estado.usuario ? 'Abrir mi cuenta' : 'Iniciar sesión o crear una cuenta'); const texto = boton.querySelector('.texto-cuenta'); if (texto) texto.textContent = boton.classList.contains('boton-cuenta') ? (nombre ? `Hola, ${nombre}` : 'Mi cuenta') : (estado.usuario ? 'Mi cuenta' : 'Cuenta'); }); }
function actualizarCarrito() {
  const cantidad = estado.carrito.reduce((total, item) => total + item.cantidad, 0); const subtotal = estado.carrito.reduce((total, item) => total + item.precio * item.cantidad, 0); const impuestos = Math.round(subtotal * 0.08);
  $('#contador-carrito').textContent = cantidad; $('#subtotal-carrito').textContent = dinero(subtotal); $('#impuestos-carrito').textContent = dinero(impuestos); $('#total-carrito').textContent = dinero(subtotal + impuestos);
  $('#items-carrito').innerHTML = estado.carrito.length ? estado.carrito.map((item, indice) => `<article class="item-carrito"><div><h3>${item.nombre}</h3><p>${item.noches} · ${dinero(item.precio)} por persona</p><div class="cantidad"><button type="button" data-accion="restar" data-indice="${indice}">−</button><span>${item.cantidad}</span><button type="button" data-accion="sumar" data-indice="${indice}">+</button></div></div><button type="button" class="eliminar-item" data-accion="eliminar" data-indice="${indice}" aria-label="Eliminar ${item.nombre}">×</button></article>`).join('') : '<div class="carrito-vacio"><span>✈</span><h3>Tu carrito está vacío</h3><p>Agregá un paquete y empezá a organizar tu próxima aventura.</p></div>';
  guardarEstado();
}
function agregarCarrito(paquete) { const existente = estado.carrito.find((item) => item.nombre === paquete.nombre); if (existente) existente.cantidad += 1; else estado.carrito.push({ ...paquete, cantidad: 1 }); actualizarCarrito(); mostrarAviso(`${paquete.nombre} se agregó al carrito.`); }
function abrirDetalle(destino, precio) { const datos = datosDestinos[destino]; const guia = guiasDestinos[destino]; if (!datos || !guia) return; estado.destinoSeleccionado = destino; const precioVisible = dinero(datos.precio || Number(precio)); $('#modal-titulo').textContent = datos.titulo; $('#modal-texto').innerHTML = `<div class="encabezado-ficha-viaje"><span>${guia.circuito}</span><strong>Desde ${precioVisible}</strong><small>${datos.duracion} · ${datos.tipo} · Precio por persona</small></div><p class="descripcion-ficha-viaje">${datos.descripcion}</p><div class="bloques-ficha-viaje"><section><h3>Incluye</h3><ul>${guia.incluye.map((item) => `<li>${item}</li>`).join('')}</ul></section><section><h3>No incluye</h3><ul><li>Vuelos internacionales, salvo indicación</li><li>Comidas no especificadas</li><li>Gastos personales y propinas</li><li>Seguro opcional y visados, si aplican</li></ul></section></div><section class="itinerario-ficha-viaje"><h3>Itinerario orientativo</h3><ol>${guia.destacados.map((item, indice) => `<li><span>Día ${indice + 1}</span>${item}</li>`).join('')}</ol></section>`; abrir('#modal'); }
function prepararTarjetasDestinos() { tarjetas.forEach((tarjeta) => { const datos = datosDestinos[tarjeta.dataset.destino]; if (!datos) return; tarjeta.dataset.precio = datos.precio; tarjeta.dataset.noches = datos.duracion; const info = tarjeta.querySelector('.info-destino'); info.querySelector('h3').textContent = datos.titulo; info.querySelector('p').textContent = datos.descripcion; const precio = info.querySelector('span:not(.chip)'); precio.textContent = `Desde ${dinero(datos.precio)}`; precio.dataset.usd = datos.precio; let meta = info.querySelector('.meta-destino'); if (!meta) { meta = document.createElement('small'); meta.className = 'meta-destino'; precio.before(meta); } meta.textContent = `${datos.duracion} · ${datos.tipo}`; const favorito = tarjeta.querySelector('.corazon'); favorito.setAttribute('aria-label', `Agregar ${tarjeta.dataset.destino} a favoritos`); const acciones = tarjeta.querySelector('.acciones-tarjeta'); if (!acciones.querySelector('.comprar-destino')) { const comprar = document.createElement('button'); comprar.type = 'button'; comprar.className = 'comprar-destino'; comprar.textContent = 'Agregar viaje'; comprar.setAttribute('aria-label', `Agregar ${tarjeta.dataset.destino} al carrito`); acciones.prepend(comprar); } }); }
function activarAuth(tipo) {
  const esLogin = tipo === 'login'; const esRegistro = tipo === 'registro';
  $$('.pestana').forEach((p) => { const activa = p.dataset.auth === tipo; p.classList.toggle('activa', activa); p.setAttribute('aria-selected', String(activa)); });
  $('#form-login').classList.toggle('oculto', !esLogin); $('#form-registro').classList.toggle('oculto', !esRegistro); $('#form-recuperar').classList.toggle('oculto', tipo !== 'recuperar');
  const primerCampo = esLogin ? '#email-login' : esRegistro ? '#nombre-registro' : '#email-recuperar';
  $(primerCampo).focus();
}
function mensajeAuth(id, mensaje, tipo = '') { const elemento = $(id); elemento.textContent = mensaje; elemento.className = `mensaje-auth ${tipo}`; }
function abrirAuth(tipo = 'login') { abrir('#modal-auth'); activarAuth(tipo); }
function normalizar(texto = '') { return texto.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim(); }
function destinosFiltrados(consulta = '', tipo = '', presupuesto = '') { const termino = normalizar(consulta); const sinonimos = { playa: ['Brasil', 'México', 'Tailandia'], europa: ['Polonia', 'Suiza', 'Italia'], america: ['Bolivia', 'Brasil', 'México'], asia: ['Japón', 'Tailandia', 'Corea del Sur'], africa: ['Egipto', 'Marruecos', 'Kenia'], oceania: ['Australia', 'Nueva Zelanda'], aventura: ['Bolivia', 'Marruecos', 'Nueva Zelanda'], cultura: ['Polonia', 'Japón', 'Egipto', 'Corea del Sur', 'Tailandia'], relax: ['Brasil', 'México', 'Tailandia'], naturaleza: ['Suiza', 'Australia', 'Nueva Zelanda'] };
  return Object.entries(datosDestinos).filter(([destino, datos]) => { const textoDestino = normalizar(`${destino} ${datos.titulo} ${datos.descripcion} ${datos.tipo}`); const coincideTexto = !termino || textoDestino.includes(termino) || (sinonimos[termino] || []).includes(destino); const coincideTipo = !tipo || datos.tipo === tipo; const coincidePrecio = !presupuesto || datos.precio <= Number(presupuesto); return coincideTexto && coincideTipo && coincidePrecio; });
}
function renderizarSugerencias() { const consulta = $('#destino').value; const resultados = destinosFiltrados(consulta).slice(0, 5); const contenedor = $('#sugerencias-busqueda'); if (!consulta.trim()) { contenedor.innerHTML = ''; return; } contenedor.innerHTML = resultados.length ? resultados.map(([destino, datos]) => `<button type="button" role="option" data-destino-sugerido="${destino}"><span>${datos.titulo}</span><small>${datos.duracion} · ${dinero(datos.precio)}</small></button>`).join('') : '<p>No encontramos coincidencias. Probá con “playa”, “aventura” o un país.</p>';
}
function renderizarResultadosBusqueda(resultados, consulta = '') { const contenedor = $('#resultado-busqueda'); if (!resultados.length) { contenedor.innerHTML = `<div class="sin-resultados"><strong>No encontramos viajes con esos filtros.</strong><span>Probá cambiar el presupuesto o elegir otra experiencia.</span></div>`; return; }
  contenedor.innerHTML = `<p class="titulo-resultados">${consulta ? `Resultados para “${consulta}”` : 'Viajes recomendados'} <span>${resultados.length}</span></p><div class="lista-resultados-busqueda">${resultados.map(([destino, datos]) => `<article><div><strong>${datos.titulo}</strong><p>${datos.descripcion}</p><small>${datos.duracion} · ${datos.tipo}</small></div><div><b>${dinero(datos.precio)}</b><button type="button" data-resultado-destino="${destino}">Ver viaje</button></div></article>`).join('')}</div>`;
}
function responderChat(texto) { const consulta = normalizar(texto); const destinosMencionados = Object.entries(datosDestinos).filter(([destino, datos]) => normalizar(`${destino} ${datos.titulo}`).includes(consulta) || consulta.includes(normalizar(destino))); const sugeridos = destinosMencionados.length ? destinosMencionados : destinosFiltrados(consulta).slice(0, 3); const todosLosDestinos = Object.entries(datosDestinos).sort(([, a], [, b]) => a.precio - b.precio);
  if (/hola|buenas|buen dia|buenas tardes/.test(consulta)) return '¡Hola! Decime un presupuesto, una experiencia o un destino; por ejemplo: “quiero playa”, “algo cultural” o “hasta USD 2.000”.';
  if (/reserva|reservar|comprar|carrito/.test(consulta)) return 'Elegí “Agregar viaje” en cualquier tarjeta, revisá el carrito y tocá “Continuar reserva”. La solicitud queda guardada en Mi cuenta; un asesor confirma disponibilidad y precio final antes de cualquier pago.';
  if (/dolar|peso|ars|cotizacion|moneda/.test(consulta)) return `El botón Moneda usa la cotización vendedora oficial para mostrar pesos argentinos. ${cotizacionDolarARS ? `La última cotización cargada es ARS ${cotizacionDolarARS.toLocaleString('es-AR')} por USD.` : 'Al cambiar a ARS se actualiza automáticamente.'} Los valores son informativos.`;
  if (/barato|economico|presupuesto|menos de|hasta/.test(consulta)) return `Las opciones más accesibles son ${todosLosDestinos.slice(0, 3).map(([, datos]) => `${datos.titulo} (${dinero(datos.precio)})`).join(', ')}. En el buscador también podés aplicar un máximo de presupuesto.`;
  if (/pareja|romantico/.test(consulta)) return `Para una escapada en pareja te recomiendo ${datosDestinos.Italia.titulo}, ${datosDestinos.Suiza.titulo} o ${datosDestinos.México.titulo}: combinan experiencias, paisajes y tiempo libre.`;
  if (/solo|sola/.test(consulta)) return `Si viajás por tu cuenta, ${datosDestinos.Japón.titulo}, ${datosDestinos.Polonia.titulo} y ${datosDestinos.Tailandia.titulo} son buenas alternativas para sumar recorridos culturales y traslados organizados.`;
  if (/familia|ninos|menores/.test(consulta)) return `Para viajar en familia, México Caribe, Brasil: Río y playas y Australia salvaje ofrecen opciones de descanso y actividades variadas. Indicá las edades al enviar la solicitud para cotizar mejor.`;
  if (/precio|incluye|impuesto|pago|cuota/.test(consulta)) return 'Los precios se muestran por persona. Cada ficha indica lo que incluye y no incluye; el carrito suma impuestos estimados y el total final se confirma antes de pagar.';
  if (/cancel|cambio|fecha/.test(consulta)) return 'Las condiciones de cambio o cancelación dependen de la tarifa y de cada proveedor. Antes de confirmar, un asesor te explicará las alternativas disponibles.';
  if (/visa|documento|pasaporte/.test(consulta)) return 'Los requisitos varían según tu nacionalidad y destino. Podemos orientarte antes de emitir la reserva, pero siempre verificá los requisitos oficiales vigentes.';
  if (sugeridos.length) return `Para lo que buscás, mirá ${sugeridos.map(([, datos]) => `${datos.titulo} (${datos.duracion}, desde ${dinero(datos.precio)})`).join(', ')}. Podés abrir su ficha para ver el itinerario y agregarlo al carrito.`;
  return 'Puedo ayudarte a elegir por presupuesto, tipo de viaje, duración o destino. Probá preguntarme por playa, aventura, cultura, una escapada en pareja o un viaje económico.';
}
function agregarMensajeChat(texto, propio = false) { const burbuja = document.createElement('p'); burbuja.textContent = texto; burbuja.className = propio ? 'mensaje-propio' : 'mensaje-asistente'; $('#chat-mensajes').append(burbuja); $('#chat-mensajes').scrollTop = $('#chat-mensajes').scrollHeight; }

$$('[data-accion="mostrar-buscador"]').forEach((boton) => boton.addEventListener('click', () => { abrir('#buscador'); $('#destino').focus(); renderizarResultadosBusqueda(destinosFiltrados()); }));
$('[data-accion="cerrar-buscador"]').addEventListener('click', () => cerrar('#buscador'));
$('[data-accion="cerrar-modal"]').addEventListener('click', () => cerrar('#modal'));
$("[data-accion=\"agregar-desde-detalle\"]").addEventListener('click', () => { const datos = datosDestinos[estado.destinoSeleccionado]; if (!datos) return; agregarCarrito({ nombre: datos.titulo, precio: datos.precio, noches: datos.duracion }); cerrar('#modal'); abrir('#carrito'); });
$$('[data-accion="abrir-carrito"]').forEach((boton) => boton.addEventListener('click', () => abrir('#carrito')));
$('[data-accion="cerrar-carrito"]').addEventListener('click', () => cerrar('#carrito'));
$('[data-accion="cerrar-auth"]').addEventListener('click', () => cerrar('#modal-auth'));
prepararTarjetasDestinos();
$$('[data-accion="ir-destinos"]').forEach((boton) => boton.addEventListener('click', () => { $('#paquetes').scrollIntoView({ behavior: 'smooth' }); mostrarAviso('Explorá nuestros paquetes y elegí tu próxima aventura.'); }));
let regionSeleccionada = 'todos';
function aplicarFiltrosDestinos() { const presupuesto = $('#filtro-precio').value; const duracion = $('#filtro-duracion').value; const tipo = $('#filtro-tipo').value; let visibles = 0; tarjetas.forEach((tarjeta) => { const datos = datosDestinos[tarjeta.dataset.destino]; const dias = Number.parseInt(datos.duracion, 10); const coincideRegion = regionSeleccionada === 'todos' || tarjeta.dataset.region === regionSeleccionada; const coincidePresupuesto = presupuesto === 'todos' || datos.precio <= Number(presupuesto); const coincideDuracion = duracion === 'todos' || (duracion === 'corta' && dias <= 7) || (duracion === 'media' && dias >= 8 && dias <= 10) || (duracion === 'larga' && dias > 10); const coincideTipo = tipo === 'todos' || datos.tipo === tipo; const visible = coincideRegion && coincidePresupuesto && coincideDuracion && coincideTipo; tarjeta.classList.toggle('oculta', !visible); if (visible) visibles += 1; }); $('#estado-filtros').textContent = visibles ? `${visibles} ${visibles === 1 ? 'viaje encontrado' : 'viajes encontrados'} · precios por persona.` : 'No encontramos viajes con esos filtros. Probá ampliar tu búsqueda.'; }
$$('.filtro').forEach((boton) => boton.addEventListener('click', () => { $$('.filtro').forEach((item) => item.classList.remove('activo')); boton.classList.add('activo'); regionSeleccionada = boton.dataset.filtro; aplicarFiltrosDestinos(); }));
$$('#filtro-precio, #filtro-duracion, #filtro-tipo').forEach((control) => control.addEventListener('change', aplicarFiltrosDestinos));
$('#pasajeros').addEventListener('change', () => { mostrarAviso(`Calcularemos alternativas para ${$('#pasajeros').selectedOptions[0].textContent.toLowerCase()}. El precio mostrado es por persona.`); });
$('[data-accion="limpiar-filtros"]').addEventListener('click', () => { regionSeleccionada = 'todos'; $$('.filtro').forEach((boton) => boton.classList.toggle('activo', boton.dataset.filtro === 'todos')); $('#filtro-precio').value = 'todos'; $('#filtro-duracion').value = 'todos'; $('#filtro-tipo').value = 'todos'; $('#pasajeros').value = '1'; aplicarFiltrosDestinos(); });
aplicarFiltrosDestinos();
tarjetas.forEach((tarjeta) => { tarjeta.querySelector('.corazon').addEventListener('click', () => { const destino = tarjeta.dataset.destino; estado.favoritos = estado.favoritos.includes(destino) ? estado.favoritos.filter((item) => item !== destino) : [...estado.favoritos, destino]; guardarEstado(); actualizarFavoritos(); mostrarAviso(`${destino} ${estado.favoritos.includes(destino) ? 'se agregó a' : 'se quitó de'} tus favoritos.`); }); tarjeta.querySelector('.detalle').addEventListener('click', () => abrirDetalle(tarjeta.dataset.destino, tarjeta.dataset.precio)); tarjeta.querySelector('.comprar-destino').addEventListener('click', () => { const datos = datosDestinos[tarjeta.dataset.destino]; agregarCarrito({ nombre: datos.titulo, precio: datos.precio, noches: datos.duracion }); abrir('#carrito'); }); });
$('[data-accion="ver-favoritos"]').addEventListener('click', () => mostrarAviso(estado.favoritos.length ? `Tus favoritos: ${estado.favoritos.join(', ')}.` : 'Todavía no agregaste destinos a favoritos.'));
$('#destino').addEventListener('input', renderizarSugerencias);
$('#sugerencias-busqueda').addEventListener('click', (evento) => { const boton = evento.target.closest('[data-destino-sugerido]'); if (!boton) return; $('#destino').value = boton.dataset.destinoSugerido; $('#sugerencias-busqueda').innerHTML = ''; $('#form-busqueda').requestSubmit(); });
$$('[data-busqueda]').forEach((boton) => boton.addEventListener('click', () => { $('#destino').value = boton.dataset.busqueda; $('#form-busqueda').requestSubmit(); }));
$('[data-accion="limpiar-busqueda"]').addEventListener('click', () => { $('#form-busqueda').reset(); $('#sugerencias-busqueda').innerHTML = ''; renderizarResultadosBusqueda(destinosFiltrados()); $('#destino').focus(); });
$('#form-busqueda').addEventListener('submit', (evento) => { evento.preventDefault(); const consulta = $('#destino').value.trim(); const resultados = destinosFiltrados(consulta, $('#tipo-buscador').value, $('#presupuesto-buscador').value); $('#sugerencias-busqueda').innerHTML = ''; renderizarResultadosBusqueda(resultados, consulta); });
$('#resultado-busqueda').addEventListener('click', (evento) => { const boton = evento.target.closest('[data-resultado-destino]'); if (!boton) return; const destino = boton.dataset.resultadoDestino; cerrar('#buscador'); abrirDetalle(destino, datosDestinos[destino].precio); });
$$('.consultar').forEach((boton) => boton.addEventListener('click', () => { cerrar('#modal'); $('#contacto').scrollIntoView({ behavior: 'smooth' }); mostrarAviso(`Recibimos tu consulta sobre ${boton.dataset.destino || estado.destinoSeleccionado}.`); }));
$$('.boton-agregar').forEach((boton) => boton.addEventListener('click', () => { const paquete = boton.closest('.paquete'); agregarCarrito({ nombre: paquete.dataset.paquete, precio: Number(paquete.dataset.precio), noches: paquete.dataset.noches }); }));
$('#items-carrito').addEventListener('click', (evento) => { const boton = evento.target.closest('button'); if (!boton) return; const indice = Number(boton.dataset.indice); if (boton.dataset.accion === 'sumar') estado.carrito[indice].cantidad += 1; if (boton.dataset.accion === 'restar') { estado.carrito[indice].cantidad -= 1; if (!estado.carrito[indice].cantidad) estado.carrito.splice(indice, 1); } if (boton.dataset.accion === 'eliminar') estado.carrito.splice(indice, 1); actualizarCarrito(); });
$('[data-accion="vaciar-carrito"]').addEventListener('click', () => { if (!estado.carrito.length) return mostrarAviso('El carrito ya está vacío.'); estado.carrito = []; actualizarCarrito(); mostrarAviso('Se vació el carrito.'); });
function obtenerTotalCarrito() { const subtotal = estado.carrito.reduce((total, item) => total + item.precio * item.cantidad, 0); return { subtotal, impuestos: Math.round(subtotal * 0.08), total: subtotal + Math.round(subtotal * 0.08) }; }
function actualizarResumenCheckout() { const { subtotal, impuestos, total } = obtenerTotalCarrito(); $('#resumen-checkout').innerHTML = `<div class="resumen-checkout-titulo"><span>Tu selección</span><b>${estado.carrito.reduce((cantidad, item) => cantidad + item.cantidad, 0)} ${estado.carrito.reduce((cantidad, item) => cantidad + item.cantidad, 0) === 1 ? 'viaje' : 'viajes'}</b></div><div class="resumen-checkout-items">${estado.carrito.map((item) => `<p><span>${item.cantidad}× ${item.nombre}<small>${item.noches} · Por persona</small></span><strong>${dinero(item.precio * item.cantidad)}</strong></p>`).join('')}</div><div class="resumen-checkout-total"><p><span>Subtotal</span><strong>${dinero(subtotal)}</strong></p><p><span>Impuestos estimados</span><strong>${dinero(impuestos)}</strong></p><p class="total"><span>Total estimado</span><strong>${dinero(total)}</strong></p></div><small class="aclaracion-checkout">El precio final y la disponibilidad se confirman con un asesor antes de cualquier pago.</small>`; }
function abrirCheckout() { const hoy = new Date().toISOString().split('T')[0]; $('#salida-checkout').min = hoy; $('#nombre-checkout').value = estado.usuario?.nombre || ''; $('#email-checkout').value = estado.usuario?.correo || ''; $('#telefono-checkout').value = estado.usuario?.telefono || ''; $('#pasajeros-checkout').value = $('#pasajeros').value; $('#mensaje-checkout').textContent = ''; actualizarResumenCheckout(); abrir('#checkout'); }
$("[data-accion=\"checkout\"]").addEventListener('click', () => { if (!estado.carrito.length) return mostrarAviso('Agregá al menos un paquete para continuar.'); if (!estado.usuario) { cerrar('#carrito'); abrirAuth('login'); mostrarAviso('Iniciá sesión para continuar con la reserva.'); } else { cerrar('#carrito'); abrirCheckout(); } });
document.addEventListener('click', (evento) => { const boton = evento.target.closest('[data-accion="abrir-login"], [data-accion="abrir-cuenta"]'); if (!boton) return; if (boton.dataset.accion === 'abrir-login') abrirAuth('login'); else mostrarCuenta(); });
$$('.pestana').forEach((boton) => boton.addEventListener('click', () => activarAuth(boton.dataset.auth)));
$$('[data-accion="ir-registro"]').forEach((boton) => boton.addEventListener('click', () => activarAuth('registro')));
$$('[data-accion="ir-login"]').forEach((boton) => boton.addEventListener('click', () => activarAuth('login')));
$$('.ver-clave').forEach((boton) => boton.addEventListener('click', () => { const campo = $(`#${boton.dataset.clave}`); const visible = campo.type === 'text'; campo.type = visible ? 'password' : 'text'; boton.textContent = visible ? 'Mostrar' : 'Ocultar'; boton.setAttribute('aria-label', visible ? 'Mostrar contraseña' : 'Ocultar contraseña'); }));
$('#form-login').addEventListener('submit', async (evento) => {
  evento.preventDefault(); const formulario = evento.currentTarget;
  if (!formulario.checkValidity()) return formulario.reportValidity();
  const correo = $('#email-login').value.trim().toLowerCase(); const perfil = perfiles.find((item) => item.correo === correo);
  if (!perfil) return mensajeAuth('#mensaje-login', 'No encontramos una cuenta con ese correo. Creá una cuenta para continuar.', 'error');
  if (perfil.claveHash && perfil.claveHash !== await hashClave($('#clave-login').value)) return mensajeAuth('#mensaje-login', 'La contraseña no es correcta. Revisala o recuperá el acceso.', 'error');
  estado.usuario = { nombre: perfil.nombre, correo: perfil.correo, telefono: perfil.telefono || '' }; guardarSesion($('#recordar-sesion').checked); actualizarUsuario(); cerrar('#modal-auth'); formulario.reset(); mostrarAviso(`¡Qué bueno verte de nuevo, ${estado.usuario.nombre.split(' ')[0]}!`);
});
$('#form-registro').addEventListener('submit', async (evento) => {
  evento.preventDefault(); const formulario = evento.currentTarget;
  if (!formulario.checkValidity()) return formulario.reportValidity();
  const nombre = $('#nombre-registro').value.trim(); const correo = $('#email-registro').value.trim().toLowerCase(); const clave = $('#clave-registro').value; const confirmar = $('#confirmar-clave').value;
  if (!/[A-Z]/.test(clave) || !/\d/.test(clave)) return mensajeAuth('#mensaje-registro', 'Tu contraseña debe incluir una mayúscula y un número.', 'error');
  if (clave !== confirmar) return mensajeAuth('#mensaje-registro', 'Las contraseñas no coinciden. Revisalas e intentá otra vez.', 'error');
  if (perfiles.some((item) => item.correo === correo)) return mensajeAuth('#mensaje-registro', 'Ya existe una cuenta con ese correo. Iniciá sesión para continuar.', 'error');
  const perfil = { nombre, correo, telefono: $('#telefono-registro').value.trim(), recibeNovedades: $('#recibir-novedades').checked, claveHash: await hashClave(clave) };
  perfiles.push(perfil); estado.usuario = { nombre: perfil.nombre, correo: perfil.correo, telefono: perfil.telefono }; guardarSesion(true); actualizarUsuario(); cerrar('#modal-auth'); formulario.reset(); mensajeAuth('#mensaje-registro', ''); mostrarAviso(`¡Tu cuenta está lista, ${estado.usuario.nombre.split(' ')[0]}! Ya podés empezar a planear tu viaje.`);
});
$('[data-accion="recuperar-clave"]').addEventListener('click', () => activarAuth('recuperar'));
$('#form-recuperar').addEventListener('submit', (evento) => { evento.preventDefault(); const formulario = evento.currentTarget; if (!formulario.checkValidity()) return formulario.reportValidity(); mensajeAuth('#mensaje-recuperar', 'Registramos tu solicitud. La recuperación por correo se habilita al conectar el sistema de emails de BITA.', 'exito'); formulario.reset(); });
$('[data-accion="mostrar-asistencia"]').addEventListener('click', () => { $('#contacto').scrollIntoView({ behavior: 'smooth' }); mostrarAviso('Nuestro equipo está disponible para ayudarte.'); });
$('.boton-menu').addEventListener('click', (evento) => { const menu = $('.menu-principal'); menu.classList.toggle('abierto'); evento.currentTarget.setAttribute('aria-expanded', menu.classList.contains('abierto')); });
$$('.menu-principal a').forEach((enlace) => enlace.addEventListener('click', () => $('.menu-principal').classList.remove('abierto')));
actualizarFavoritos(); actualizarCarrito(); actualizarUsuario();

let segundosOferta = 8 * 60 * 60;
function actualizarOferta() { const h = Math.floor(segundosOferta / 3600); const m = Math.floor((segundosOferta % 3600) / 60); const s = segundosOferta % 60; $('#horas').textContent = String(h).padStart(2, '0'); $('#minutos').textContent = String(m).padStart(2, '0'); $('#segundos').textContent = String(s).padStart(2, '0'); if (segundosOferta > 0) segundosOferta -= 1; }
actualizarOferta(); setInterval(actualizarOferta, 1000);
$$('.pregunta').forEach((pregunta) => pregunta.addEventListener('click', () => { const abrirEsta = !pregunta.classList.contains('abierta'); $$('.pregunta').forEach((item) => { item.classList.remove('abierta'); item.nextElementSibling.classList.remove('visible'); item.querySelector('span').textContent = '+'; }); if (abrirEsta) { pregunta.classList.add('abierta'); pregunta.nextElementSibling.classList.add('visible'); pregunta.querySelector('span').textContent = '−'; } }));
function actualizarMoneda() { document.querySelectorAll('.paquete-pie strong,.info-destino>span,.ficha-cabecera strong').forEach((elemento) => { if (!elemento.dataset.usd) { const numero = elemento.textContent.replace(/[^0-9]/g, ''); elemento.dataset.usd = numero || '0'; } elemento.textContent = dinero(Number(elemento.dataset.usd)); }); renderizarResultadosBusqueda(destinosFiltrados($('#destino').value, $('#tipo-buscador').value, $('#presupuesto-buscador').value), $('#destino').value.trim()); }
$('[data-accion="cambiar-moneda"]').addEventListener('click', async (e) => { monedaARS = !monedaARS; e.currentTarget.querySelector('b').textContent = monedaARS ? 'ARS' : 'USD'; if (monedaARS) await cargarCotizacionDolar(); actualizarMoneda(); actualizarCarrito(); actualizarEstadoCotizacion(); mostrarAviso(monedaARS ? `Precios convertidos a pesos argentinos con dólar oficial${cotizacionDolarARS ? `: ARS ${cotizacionDolarARS.toLocaleString('es-AR')}` : ''}.` : 'Precios mostrados en dólares estadounidenses.'); });
$$('[data-accion="comparar"]').forEach((boton) => boton.addEventListener('click', () => { const a = $('#comparar-a').value; const b = $('#comparar-b').value; if (!a || !b) { $('#resultado-comparador').textContent = 'Elegí dos destinos para poder compararlos.'; return; } const viajeA = datosViajes[a]; const viajeB = datosViajes[b]; $('#resultado-comparador').innerHTML = `<strong>Comparación rápida</strong><br>Precio: ${a} ${viajeA[0]} · ${b} ${viajeB[0]}<br>Duración: ${viajeA[1]} · ${viajeB[1]}<br>Experiencia: ${viajeA[2]} · ${viajeB[2]}`; }));
$$('[data-accion="ver-mapa"]').forEach((boton) => boton.addEventListener('click', () => { $('#viajes').scrollIntoView({ behavior: 'smooth' }); mostrarAviso('Usá los filtros de región para explorar los destinos.'); }));
$('[data-accion="oferta"]').addEventListener('click', () => { const bolivia = $('.tarjeta-destino.bolivia'); agregarCarrito({ nombre: 'Bolivia - Oferta relámpago', precio: 842, noches: '7 días' }); abrir('#carrito'); bolivia.scrollIntoView({ behavior: 'smooth' }); });
$('[data-accion="cerrar-checkout"]').addEventListener('click', () => cerrar('#checkout'));
$('#form-checkout').addEventListener('submit', (e) => {
  e.preventDefault(); const formulario = e.currentTarget;
  if (!formulario.checkValidity()) return formulario.reportValidity();
  if (!estado.carrito.length) return $('#mensaje-checkout').textContent = 'Tu selección está vacía. Volvé al carrito para elegir un viaje.';
  const { total } = obtenerTotalCarrito(); const codigo = `BITA-${Math.floor(100000 + Math.random() * 900000)}`;
  const reserva = { codigo, creadoEl: new Date().toLocaleDateString('es-AR'), nombre: $('#nombre-checkout').value.trim(), correo: $('#email-checkout').value.trim().toLowerCase(), telefono: $('#telefono-checkout').value.trim(), salida: $('#salida-checkout').value, pasajeros: $('#pasajeros-checkout').value, habitacion: $('#habitacion-checkout').value, comentarios: $('#comentarios-checkout').value.trim(), items: estado.carrito.map((item) => ({ ...item })), total, estado: 'Pendiente de confirmación' };
  estado.reservas.unshift(reserva); estado.carrito = []; guardarEstado(); actualizarCarrito(); cerrar('#checkout'); $('#texto-confirmacion').textContent = `Registramos tu solicitud ${codigo}. Un asesor te contactará para confirmar disponibilidad y precio final antes de cualquier pago.`; abrir('#confirmacion'); formulario.reset();
});
$('[data-accion="cerrar-confirmacion"]').addEventListener('click', () => cerrar('#confirmacion'));
$('[data-accion="abrir-chat"]').addEventListener('click', () => { $('#chat').classList.add('abierto'); $('#mensaje-chat').focus(); });
$('[data-accion="cerrar-chat"]').addEventListener('click', () => $('#chat').classList.remove('abierto'));
function enviarConsultaChat(texto) { const consulta = texto.trim(); if (!consulta) return; agregarMensajeChat(consulta, true); $('#mensaje-chat').value = ''; window.setTimeout(() => agregarMensajeChat(responderChat(consulta)), 350); }
$('#form-chat').addEventListener('submit', (e) => { e.preventDefault(); enviarConsultaChat($('#mensaje-chat').value); });
$$('[data-chat]').forEach((boton) => boton.addEventListener('click', () => enviarConsultaChat(boton.dataset.chat)));
function mostrarCuenta(tab = 'reservas') { if (!estado.usuario) { abrirAuth('login'); return; } const reservasUsuario = estado.reservas.filter((reserva) => reserva.correo === estado.usuario.correo); $('#nombre-cuenta').textContent = estado.usuario.nombre; $('#contenido-cuenta').innerHTML = tab === 'reservas' ? (reservasUsuario.length ? `<div class="lista-reservas">${reservasUsuario.map((reserva) => `<article class="reserva-cuenta"><span>${reserva.estado}</span><h3>${reserva.items.map((item) => item.nombre).join(' + ')}</h3><p>Código ${reserva.codigo} · Salida estimada: ${new Date(`${reserva.salida}T12:00:00`).toLocaleDateString('es-AR')}</p><strong>${dinero(reserva.total)} estimado</strong></article>`).join('')}</div>` : '<p>No tenés solicitudes todavía.</p><p>Cuando envíes una reserva, vas a poder seguirla desde acá.</p>') : tab === 'guardados' ? `<p>${estado.favoritos.length ? estado.favoritos.join(', ') : 'No guardaste destinos aún.'}</p>` : `<p><b>Correo:</b> ${estado.usuario.correo}</p><p><b>WhatsApp:</b> ${estado.usuario.telefono || 'No informado'}</p><button class="link-form" data-accion="cerrar-sesion">Cerrar sesión</button>`; $('#panel-cuenta').classList.add('abierto'); }
document.addEventListener('click', (e) => { const b = e.target.closest('[data-accion="cerrar-sesion"]'); if (b && b.closest('#panel-cuenta')) { cerrarSesion(); $('#panel-cuenta').classList.remove('abierto'); mostrarAviso('Sesión cerrada.'); } });
$$('.tabs-cuenta button').forEach((b) => b.addEventListener('click', () => mostrarCuenta(b.dataset.tab)));
$('[data-accion="cerrar-cuenta"]').addEventListener('click', () => $('#panel-cuenta').classList.remove('abierto'));
