const estado = {
  favoritos: JSON.parse(localStorage.getItem('bitaFavoritos')) || [],
  carrito: JSON.parse(localStorage.getItem('bitaCarrito')) || [],
  destinoSeleccionado: '', usuario: JSON.parse(localStorage.getItem('bitaUsuario')) || null
};
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const tarjetas = $$('.tarjeta-destino');
const datosViajes = { 'Japón': ['USD 2.850', '12 días', 'Cultural'], 'Italia': ['USD 1.950', '10 días', 'Gastronomía'], 'Marruecos': ['USD 1.780', '9 días', 'Aventura'], 'Australia': ['USD 3.400', '14 días', 'Naturaleza'], 'Corea del Sur': ['USD 2.490', '11 días', 'Cultural'], 'México': ['USD 1.050', '8 días', 'Relax'], 'Kenia': ['USD 3.150', '10 días', 'Safari'], 'Nueva Zelanda': ['USD 3.650', '14 días', 'Aventura'] };
let temporizadorAviso;
let monedaARS = false;
function dinero(valor) { const monto = Number(valor); return monedaARS ? `ARS ${(monto * 1100).toLocaleString('es-AR')}` : `USD ${monto.toLocaleString('es-AR')}`; }
function guardarEstado() { localStorage.setItem('bitaFavoritos', JSON.stringify(estado.favoritos)); localStorage.setItem('bitaCarrito', JSON.stringify(estado.carrito)); localStorage.setItem('bitaUsuario', JSON.stringify(estado.usuario)); }
function mostrarAviso(mensaje) { clearTimeout(temporizadorAviso); $('#aviso').textContent = mensaje; $('#aviso').classList.add('visible'); temporizadorAviso = setTimeout(() => $('#aviso').classList.remove('visible'), 3200); }
function abrir(selector) { $(selector).classList.add('abierto'); $(selector).setAttribute('aria-hidden', 'false'); }
function cerrar(selector) { $(selector).classList.remove('abierto'); $(selector).setAttribute('aria-hidden', 'true'); }
function actualizarFavoritos() { $('#contador-favoritos').textContent = estado.favoritos.length; tarjetas.forEach((tarjeta) => { const activo = estado.favoritos.includes(tarjeta.dataset.destino); const boton = tarjeta.querySelector('.corazon'); boton.textContent = activo ? '♥' : '♡'; boton.classList.toggle('seleccionado', activo); }); }
function actualizarUsuario() { const boton = $('[data-accion="abrir-login"], [data-accion="cerrar-sesion"]'); boton.textContent = estado.usuario ? `Hola, ${estado.usuario.nombre.split(' ')[0]}` : 'Ingresar'; boton.dataset.accion = estado.usuario ? 'cerrar-sesion' : 'abrir-login'; }
function actualizarCarrito() {
  const cantidad = estado.carrito.reduce((total, item) => total + item.cantidad, 0); const subtotal = estado.carrito.reduce((total, item) => total + item.precio * item.cantidad, 0); const impuestos = Math.round(subtotal * 0.08);
  $('#contador-carrito').textContent = cantidad; $('#subtotal-carrito').textContent = dinero(subtotal); $('#impuestos-carrito').textContent = dinero(impuestos); $('#total-carrito').textContent = dinero(subtotal + impuestos);
  $('#items-carrito').innerHTML = estado.carrito.length ? estado.carrito.map((item, indice) => `<article class="item-carrito"><div><h3>${item.nombre}</h3><p>${item.noches} · ${dinero(item.precio)} por persona</p><div class="cantidad"><button type="button" data-accion="restar" data-indice="${indice}">−</button><span>${item.cantidad}</span><button type="button" data-accion="sumar" data-indice="${indice}">+</button></div></div><button type="button" class="eliminar-item" data-accion="eliminar" data-indice="${indice}" aria-label="Eliminar ${item.nombre}">×</button></article>`).join('') : '<div class="carrito-vacio"><span>✈</span><h3>Tu carrito está vacío</h3><p>Agregá un paquete y empezá a organizar tu próxima aventura.</p></div>';
  guardarEstado();
}
function agregarCarrito(paquete) { const existente = estado.carrito.find((item) => item.nombre === paquete.nombre); if (existente) existente.cantidad += 1; else estado.carrito.push({ ...paquete, cantidad: 1 }); actualizarCarrito(); mostrarAviso(`${paquete.nombre} se agregó al carrito.`); }
function abrirDetalle(destino, precio) { estado.destinoSeleccionado = destino; $('#modal-titulo').textContent = `Viaje a ${destino}`; $('#modal-texto').innerHTML = `Este programa está disponible desde <b>${precio}</b>.<br><br><b>Incluye:</b> alojamiento seleccionado, asistencia al viajero y guía local.<br><b>Itinerario:</b> llegada y bienvenida · recorridos destacados · día libre · regreso.<br><br>Elegí tu fecha y te enviamos una propuesta personalizada.`; abrir('#modal'); }
function activarAuth(tipo) { $$('.pestana').forEach((p) => p.classList.toggle('activa', p.dataset.auth === tipo)); $('#form-login').classList.toggle('oculto', tipo !== 'login'); $('#form-registro').classList.toggle('oculto', tipo !== 'registro'); }

$$('[data-accion="mostrar-buscador"]').forEach((boton) => boton.addEventListener('click', () => { abrir('#buscador'); $('#destino').focus(); }));
$('[data-accion="cerrar-buscador"]').addEventListener('click', () => cerrar('#buscador'));
$('[data-accion="cerrar-modal"]').addEventListener('click', () => cerrar('#modal'));
$$('[data-accion="abrir-carrito"]').forEach((boton) => boton.addEventListener('click', () => abrir('#carrito')));
$('[data-accion="cerrar-carrito"]').addEventListener('click', () => cerrar('#carrito'));
$('[data-accion="cerrar-auth"]').addEventListener('click', () => cerrar('#modal-auth'));
$$('[data-accion="ir-destinos"]').forEach((boton) => boton.addEventListener('click', () => { $('#paquetes').scrollIntoView({ behavior: 'smooth' }); mostrarAviso('Explorá nuestros paquetes y elegí tu próxima aventura.'); }));
$$('.filtro').forEach((boton) => boton.addEventListener('click', () => { $$('.filtro').forEach((item) => item.classList.remove('activo')); boton.classList.add('activo'); tarjetas.forEach((tarjeta) => tarjeta.classList.toggle('oculta', boton.dataset.filtro !== 'todos' && tarjeta.dataset.region !== boton.dataset.filtro)); }));
tarjetas.forEach((tarjeta) => { tarjeta.querySelector('.corazon').addEventListener('click', () => { const destino = tarjeta.dataset.destino; estado.favoritos = estado.favoritos.includes(destino) ? estado.favoritos.filter((item) => item !== destino) : [...estado.favoritos, destino]; guardarEstado(); actualizarFavoritos(); mostrarAviso(`${destino} ${estado.favoritos.includes(destino) ? 'se agregó a' : 'se quitó de'} tus favoritos.`); }); tarjeta.querySelector('.detalle').addEventListener('click', () => abrirDetalle(tarjeta.dataset.destino, tarjeta.dataset.precio)); });
$('[data-accion="ver-favoritos"]').addEventListener('click', () => mostrarAviso(estado.favoritos.length ? `Tus favoritos: ${estado.favoritos.join(', ')}.` : 'Todavía no agregaste destinos a favoritos.'));
$('#form-busqueda').addEventListener('submit', (evento) => { evento.preventDefault(); const buscado = $('#destino').value.trim().toLowerCase(); const encontrado = tarjetas.find((t) => t.dataset.destino.toLowerCase().includes(buscado)); if (encontrado) { cerrar('#buscador'); abrirDetalle(encontrado.dataset.destino, encontrado.dataset.precio); } else $('#resultado-busqueda').textContent = `No encontramos “${buscado}”, pero podemos armar un viaje a medida.`; });
$$('.consultar').forEach((boton) => boton.addEventListener('click', () => { cerrar('#modal'); $('#contacto').scrollIntoView({ behavior: 'smooth' }); mostrarAviso(`Recibimos tu consulta sobre ${boton.dataset.destino || estado.destinoSeleccionado}.`); }));
$$('.boton-agregar').forEach((boton) => boton.addEventListener('click', () => { const paquete = boton.closest('.paquete'); agregarCarrito({ nombre: paquete.dataset.paquete, precio: Number(paquete.dataset.precio), noches: paquete.dataset.noches }); }));
$('#items-carrito').addEventListener('click', (evento) => { const boton = evento.target.closest('button'); if (!boton) return; const indice = Number(boton.dataset.indice); if (boton.dataset.accion === 'sumar') estado.carrito[indice].cantidad += 1; if (boton.dataset.accion === 'restar') { estado.carrito[indice].cantidad -= 1; if (!estado.carrito[indice].cantidad) estado.carrito.splice(indice, 1); } if (boton.dataset.accion === 'eliminar') estado.carrito.splice(indice, 1); actualizarCarrito(); });
$('[data-accion="vaciar-carrito"]').addEventListener('click', () => { if (!estado.carrito.length) return mostrarAviso('El carrito ya está vacío.'); estado.carrito = []; actualizarCarrito(); mostrarAviso('Se vació el carrito.'); });
$('[data-accion="checkout"]').addEventListener('click', () => { if (!estado.carrito.length) return mostrarAviso('Agregá al menos un paquete para continuar.'); if (!estado.usuario) { cerrar('#carrito'); abrir('#modal-auth'); activarAuth('login'); mostrarAviso('Iniciá sesión para continuar con la reserva.'); } else { cerrar('#carrito'); abrir('#checkout'); } });
document.addEventListener('click', (evento) => { const boton = evento.target.closest('[data-accion="abrir-login"], [data-accion="cerrar-sesion"]'); if (!boton) return; if (boton.dataset.accion === 'abrir-login') { abrir('#modal-auth'); activarAuth('login'); } else { estado.usuario = null; guardarEstado(); actualizarUsuario(); mostrarAviso('Cerraste sesión correctamente.'); } });
$$('.pestana').forEach((boton) => boton.addEventListener('click', () => activarAuth(boton.dataset.auth)));
$('#form-login').addEventListener('submit', (evento) => { evento.preventDefault(); const correo = $('#email-login').value; estado.usuario = { nombre: correo.split('@')[0], correo }; guardarEstado(); actualizarUsuario(); cerrar('#modal-auth'); mostrarAviso(`¡Bienvenido a BITA, ${estado.usuario.nombre}!`); });
$('#form-registro').addEventListener('submit', (evento) => { evento.preventDefault(); estado.usuario = { nombre: $('#nombre-registro').value.trim(), correo: $('#email-registro').value }; guardarEstado(); actualizarUsuario(); cerrar('#modal-auth'); mostrarAviso(`¡Tu cuenta está lista, ${estado.usuario.nombre}!`); evento.target.reset(); });
$('[data-accion="recuperar-clave"]').addEventListener('click', () => mostrarAviso('Te enviaríamos un enlace de recuperación a tu correo.'));
$('[data-accion="mostrar-asistencia"]').addEventListener('click', () => { $('#contacto').scrollIntoView({ behavior: 'smooth' }); mostrarAviso('Nuestro equipo está disponible para ayudarte.'); });
$('.boton-menu').addEventListener('click', (evento) => { const menu = $('.menu-principal'); menu.classList.toggle('abierto'); evento.currentTarget.setAttribute('aria-expanded', menu.classList.contains('abierto')); });
$$('.menu-principal a').forEach((enlace) => enlace.addEventListener('click', () => $('.menu-principal').classList.remove('abierto')));
actualizarFavoritos(); actualizarCarrito(); actualizarUsuario();

let segundosOferta = 8 * 60 * 60;
function actualizarOferta() { const h = Math.floor(segundosOferta / 3600); const m = Math.floor((segundosOferta % 3600) / 60); const s = segundosOferta % 60; $('#horas').textContent = String(h).padStart(2, '0'); $('#minutos').textContent = String(m).padStart(2, '0'); $('#segundos').textContent = String(s).padStart(2, '0'); if (segundosOferta > 0) segundosOferta -= 1; }
actualizarOferta(); setInterval(actualizarOferta, 1000);
$$('.pregunta').forEach((pregunta) => pregunta.addEventListener('click', () => { const abrirEsta = !pregunta.classList.contains('abierta'); $$('.pregunta').forEach((item) => { item.classList.remove('abierta'); item.nextElementSibling.classList.remove('visible'); item.querySelector('span').textContent = '+'; }); if (abrirEsta) { pregunta.classList.add('abierta'); pregunta.nextElementSibling.classList.add('visible'); pregunta.querySelector('span').textContent = '−'; } }));
function actualizarMoneda() { document.querySelectorAll('.paquete-pie strong,.info-destino>span,.ficha-cabecera strong').forEach((elemento) => { if (!elemento.dataset.usd) { const numero = elemento.textContent.replace(/[^0-9]/g, ''); elemento.dataset.usd = numero || '0'; } const precio = Number(elemento.dataset.usd); elemento.textContent = monedaARS ? `ARS ${(precio * 1100).toLocaleString('es-AR')}` : `USD ${precio.toLocaleString('es-AR')}`; }); }
$('[data-accion="cambiar-moneda"]').addEventListener('click', (e) => { monedaARS = !monedaARS; e.currentTarget.querySelector('b').textContent = monedaARS ? 'ARS' : 'USD'; actualizarMoneda(); actualizarCarrito(); mostrarAviso(`Precios mostrados en ${monedaARS ? 'pesos argentinos' : 'dólares estadounidenses'}.`); });
$$('[data-accion="comparar"]').forEach((boton) => boton.addEventListener('click', () => { const a = $('#comparar-a').value; const b = $('#comparar-b').value; if (!a || !b) { $('#resultado-comparador').textContent = 'Elegí dos destinos para poder compararlos.'; return; } const viajeA = datosViajes[a]; const viajeB = datosViajes[b]; $('#resultado-comparador').innerHTML = `<strong>Comparación rápida</strong><br>Precio: ${a} ${viajeA[0]} · ${b} ${viajeB[0]}<br>Duración: ${viajeA[1]} · ${viajeB[1]}<br>Experiencia: ${viajeA[2]} · ${viajeB[2]}`; }));
$$('[data-accion="ver-mapa"]').forEach((boton) => boton.addEventListener('click', () => { $('#viajes').scrollIntoView({ behavior: 'smooth' }); mostrarAviso('Usá los filtros de región para explorar los destinos.'); }));
$('[data-accion="oferta"]').addEventListener('click', () => { const bolivia = $('.tarjeta-destino.bolivia'); agregarCarrito({ nombre: 'Bolivia - Oferta relámpago', precio: 842, noches: '7 días' }); abrir('#carrito'); bolivia.scrollIntoView({ behavior: 'smooth' }); });
$('[data-accion="cerrar-checkout"]').addEventListener('click', () => cerrar('#checkout'));
$('#form-checkout').addEventListener('submit', (e) => { e.preventDefault(); const codigo = `BITA-${Math.floor(100000 + Math.random() * 900000)}`; estado.carrito = []; actualizarCarrito(); cerrar('#checkout'); $('#texto-confirmacion').textContent = `Tu solicitud fue registrada con el código ${codigo}. En breve recibirás los detalles por correo.`; abrir('#confirmacion'); e.target.reset(); });
$('[data-accion="cerrar-confirmacion"]').addEventListener('click', () => cerrar('#confirmacion'));
$('[data-accion="abrir-chat"]').addEventListener('click', () => $('#chat').classList.add('abierto'));
$('[data-accion="cerrar-chat"]').addEventListener('click', () => $('#chat').classList.remove('abierto'));
$('#form-chat').addEventListener('submit', (e) => { e.preventDefault(); const texto = e.target.querySelector('input').value.trim(); $('#chat-mensajes').insertAdjacentHTML('beforeend', `<p class="mensaje-propio">${texto}</p>`); e.target.reset(); setTimeout(() => $('#chat-mensajes').insertAdjacentHTML('beforeend', '<p>Gracias, un asesor te responderá a la brevedad.</p>'), 500); });
function mostrarCuenta(tab = 'reservas') { if (!estado.usuario) { abrir('#modal-auth'); return; } $('#nombre-cuenta').textContent = estado.usuario.nombre; $('#contenido-cuenta').innerHTML = tab === 'reservas' ? '<p>No tenés reservas confirmadas todavía.</p><p>Cuando completes una solicitud aparecerá aquí.</p>' : tab === 'guardados' ? `<p>${estado.favoritos.length ? estado.favoritos.join(', ') : 'No guardaste destinos aún.'}</p>` : `<p><b>Correo:</b> ${estado.usuario.correo}</p><button class="link-form" data-accion="cerrar-sesion">Cerrar sesión</button>`; $('#panel-cuenta').classList.add('abierto'); }
document.addEventListener('click', (e) => { const b = e.target.closest('[data-accion="cerrar-sesion"]'); if (b && b.closest('#panel-cuenta')) { estado.usuario = null; guardarEstado(); actualizarUsuario(); $('#panel-cuenta').classList.remove('abierto'); mostrarAviso('Sesión cerrada.'); } });
$('.boton-cuenta').addEventListener('dblclick', () => mostrarCuenta());
$$('.tabs-cuenta button').forEach((b) => b.addEventListener('click', () => mostrarCuenta(b.dataset.tab)));
$('[data-accion="cerrar-cuenta"]').addEventListener('click', () => $('#panel-cuenta').classList.remove('abierto'));
